"""empty message

Revision ID: a2320417d5bc
Revises: a3ad152392f8
Create Date: 2022-06-07 20:12:27.581733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2320417d5bc'
down_revision = 'a3ad152392f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('city_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'artist', 'city', ['city_id'], ['id'])
    op.drop_column('artist', 'city')
    op.add_column('venue', sa.Column('city_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'venue', 'city', ['city_id'], ['id'])
    op.drop_column('venue', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'venue', type_='foreignkey')
    op.drop_column('venue', 'city_id')
    op.add_column('artist', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'artist', type_='foreignkey')
    op.drop_column('artist', 'city_id')
    # ### end Alembic commands ###
